CREATE TABLE IF NOT EXISTS "clients" (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    STREET VARCHAR(255) NOT NULL,
    STREET_NUMBER INT NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    ZIP_CODE INT NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "restaurateurs" (
    ID SERIAL PRIMARY KEY,
    ID_RESTAURANT INT NOT NULL 
);

CREATE TABLE IF NOT EXISTS "moderateurs" (
    ID SERIAL PRIMARY KEY,
    ID_CLIENT INT NOT NULL 
);

CREATE TABLE IF NOT EXISTS "restaurants" (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    STREET VARCHAR(255) NOT NULL,
    STREET_NUMBER INT NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    ZIP_CODE INT NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    FOOD_TYPE VARCHAR(255) NOT NULL,
    MENU INT NOT NULL,
    PRICE_RANGE INT NOT NULL,
    AVERAGE_RATING FLOAT NOT NULL,
    OPENING_TIME INT NOT NULL,
    CLOSING_TIME INT NOT NULL,
    DELIVERY BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "menus" (
    ID SERIAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS "plats" (
    ID SERIAL PRIMARY KEY,
    MENU INT,
    NAME VARCHAR(255) NOT NULL,
    PRICE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS "allergenes" (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "plats_allergenes" (
    ID_PLAT INT NOT NULL,
    ID_ALLERGENE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS "notes" (
    ID SERIAL PRIMARY KEY,
    ID_CLIENT INT NOT NULL,
    ID_RESTAURANT INT NOT NULL,
    DATE_RATING DATE NOT NULL, 
    COMMENT VARCHAR(255) NOT NULL,
    NOTE INT NOT NULL,
    RECOMMANDATION BOOLEAN NOT NULL,
    NOTE_DELIVERY INT NOT NULL,
    NOTE_PHYSICAL INT NOT NULL,
    ORDERED_PLATS INT,
    FOREIGN KEY (ID_CLIENT) REFERENCES clients(ID),
    FOREIGN KEY (ID_RESTAURANT) REFERENCES restaurants(ID),
    PRICE_NOTE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS "notes_supprimees" (
    ID INT PRIMARY KEY,
    ID_MODERATEUR INT NOT NULL,
    ID_CLIENT INT NOT NULL,
    ID_RESTAURANT INT NOT NULL,
    DATE_RATING DATE NOT NULL,
    COMMENT VARCHAR(255) NOT NULL,
    NOTE INT NOT NULL,
    RECOMMANDATION BOOLEAN NOT NULL,
    NOTE_DELIVERY INT NOT NULL,
    NOTE_PHYSICAL INT NOT NULL,
    ORDERED_PLATS INT,
    FOREIGN KEY (ID_MODERATEUR) REFERENCES moderateurs(ID),
    FOREIGN KEY (ID_RESTAURANT) REFERENCES restaurants(ID),
    PRICE_NOTE INT NOT NULL
);